### ISSUE TITLE
[Suggestion] use `AddComponentMenu` attributes for components

### ISSUE THREAD

**Issue by UlyssesWu** [Real-Serious-Games/Unity-Weld#16]
When I add components for UI objects (Text, Slider etc.), I have to find OneWayPropertyBinding through (I don't want to use keyboard🤣 ):

> Add Component -> Scripts -> UnityWeld.Bindings -> One Way Property Binding

However, if you could add `[AddComponentMenu("Unity Weld/OneWay Property Binding")]` beyond `public class OneWayPropertyBinding : AbstractMemberBinding`, we can simply the process:

> Add Component ->Unity Weld -> One Way Property Binding

**Comment by UlyssesWu** [comment]
Another trouble when using UnityWeld is that it doesn't seems to support EventBinding with parameters... such as this:

![unity-weld-8](https://user-images.githubusercontent.com/4312781/40623082-9b616bf0-62d7-11e8-9f76-e1c45295bb25.png)

It can't be replaced by EventBinding.

**Comment by RoryDungan** [comment]
Thanks for that suggestion! I normally always just search for the component by name but you're right, having them in an easily accessible menu would make it easier to use and also easier for a new user to see all the components available to them. 

We'd be happy if you wanted to submit a pull request with the `AddComponentMenu` attributes. I'll add it to our backlog too but since we're working on some other projects at RSG at the moment and there are a few other things I want to do on Unity Weld too like the DropdownBinding inspector, I'm afraid I can't say when we'd have time to work on it ourselves.

Default parameters in event bindings is a useful feature on Unity events but I'm not sure how they could be easily implemented in Unity Weld. I'm not completely happy with how Unity does it because it's very easy to accidentally bind to the version of an event that takes a default parameter when you meant to bind to a method with a parameter, so we'd need to come up with a good way of presenting it to users.

**Comment by UlyssesWu** [comment]
One more trouble I met is that ToggleActiveBinding toggles active for all childrens, but usually I just want to toggle active for the gameobject itself. I tried adding a "Self Only" bool & checkbox for ToggleActiveBinding, and using following code to toggle active. It works but requires the object to be active when the scene start, otherwise the binding won't even get the chance to initialize so it won't work... 🤔 

        private void SetAllChildrenActive(bool active)
        {
            if (SelfOnly)
            {
                transform.gameObject.SetActive(active);
                return;
            }

            foreach (Transform child in transform)
            {
                child.gameObject.SetActive(active);
            }
        }

**Comment by MorganMoon** [comment]
@UlyssesWu I've tried that exact thing before and ran into the same issues, and I decided to look into solving the issue with initialization a little more this morning, and found we could use something like this: https://docs.unity3d.com/ScriptReference/RuntimeInitializeOnLoadMethodAttribute.html rather than Awake and do something like this:

```
public class WeldContext
{
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    public static void WeldContextStartup()
    {
        SceneManager.sceneLoaded += SceneManager_SceneLoaded;
    }

    static void SceneManager_SceneLoaded(Scene arg0, LoadSceneMode arg1)
    {
        foreach(var parentT in arg0.GetRootGameObjects())
        {
            //Call Init() on all bindings
        }
    }
}
```

**Comment by RoryDungan** [comment]
I was not aware of `RuntimeInitializeOnLoadMethodAttribute` but that looks like it could be a good solution for initialising components on objects that are turned off. 

The main reason we originally chose to make the ToggleActiveBinding toggle its children, not itself, is that as you saw, if an object is turned off when the game starts its `Awake()` and `Start()` methods won't be called. Toggling children isn't the most intuitive behaviour for this component as it means you need to nest everything underneath it one more level than you otherwise would, but it's more intuitive than the component not working when it starts turned off.

I'd be keen to add a version that can toggle itself but I'd probably rather if that became a new component, say `ToggleSelfBinding`, becuase changing the existing `ToggleActiveBinding` could break backwards compatibility. I've closed this issue because the original topic was resolved but feel free to open a new one for the `ToggleActiveBinding` feature.

**Comment by UlyssesWu** [comment]
Thanks to both of you! 🙏
