### ISSUE TITLE
Binding through custom string instead of function name

### ISSUE THREAD

**Issue by sebas77** [Real-Serious-Games/Unity-Weld#29]
Is it possible somehow to bind callbacks through strings instead of function names?

Something like 

[Binding("BindingName")]

so that BindingName will be actually shown in the dropbox instead of the method of the class? 

This is needed to allow refactoring, so that I can change the name of the method without needing to touch the UI.

Is a similar solution already available?

**Comment by RoryDungan** [comment]
Unfortunately that isn't currently available, although it is on our [roadmap](https://trello.com/c/ZPosyjBu/43-allow-binding-name-to-be-set-explicitly-to-a-string-using-the-binding-attribute-instead-of-always-taking-the-class-name). If you'd like to look into it and submit a pull request that would be awesome, otherwise I'll update this issue when eventually gets implemented although I'm afraid I can't offer any ETA at the moment.

**Comment by sebas77** [comment]
Your code is very well written, but at first try I didn't figure out were the bindings are looked for. However I am not sure if I am going to end up using this solution as it may clash with our current ecs design. For the time being I close the issue thanks for the explanation

**Comment by RoryDungan** [comment]
If in future you ever did want to look into this, the place to start would probably be to change [`BindableMember`](https://github.com/Real-Serious-Games/Unity-Weld/blob/master/UnityWeld/Binding/Internal/BindableMember.cs) so that `MemberName` can be cached as a custom string rather than coming directly from the reflected `MemberInfo` object. Once we can store that data, [`TypeResolver.FindBindableProperties`](https://github.com/Real-Serious-Games/Unity-Weld/blob/master/UnityWeld/Binding/Internal/TypeResolver.cs#L243) and [`TypeResolver.FindBindableMethods`](https://github.com/Real-Serious-Games/Unity-Weld/blob/master/UnityWeld/Binding/Internal/TypeResolver.cs#L291) are the functions that actually find all the members with the `Binding` attribute. 

I'll update this if I get a chance to look into it more.
