### ISSUE TITLE
Ahead of time Compilation Problem with Binding on iOS

### ISSUE THREAD

**Issue by step4** [Real-Serious-Games/Unity-Weld#34]
When I try to run my game on an iOS Device and use the Collection-Binding I get an error after setting the BindableCollection. XCode shows:
```ExecutionEngineException: Attempting to call method 'UnityWeld.Binding.Internal.UnityEventBinder`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]::.ctor' for which no ahead of time (AOT) code was generated.```

I tried managed bytcode stripping with the link.xml file and content:
```
<linker>
    <assembly fullname="UnityWeld" preserve="all"/>
    <assembly fullname="UnityWeld.Binding" preserve="all"/>
    <assembly fullname="UnityWeld.Binding.Internal" preserve="all"/>
</linker>
```

but with no success.

Is there some workarounds for that?

**Comment by RoryDungan** [comment]
Interesting. I'm currently using Unity Weld and collection binding on iOS and have it working. Did you just include the source in your Unity project or did you use the pre-built DLL? If you included the source, can you check that `AOTOptimisationHelper.cs` is present? 

Basically what this is saying is that Unity Weld is trying to create an instance of `UnityEventBinder<bool>`, but that class doesn't exist. With Mono this is no problem because the JIT can create the new class, but IL2CPP can only create instances of classes that were known at compile time. The solution to this is to have a reference to the generic type you want (in this case, `UnityEventBinder<bool>`) somewhere in your code, even if that code is never reached at runtime, because its presence will be enough to let the compiler know that generic class should be included in the build. This is what `AOTOptimisationHelper.cs` does though, so I'm not sure why it's breaking for you. Perhaps there's some compiler optimisation removing code that's never being called?

**Comment by step4** [comment]
The `AOTOptimisationHelper.cs` fixed everything! Thanks.
I copied the source files and did not see this file somehow.

**Comment by marijneken** [comment]
You just saved my life! I noticed my folder structure is different from what's in this repository. So my local copy of the source must be older than 3 years I guess. In either case, that particular file was missing and after adding it, everything was fine when building with IL2CPP. Thanks @RoryDungan.
